import { useCallback, useMemo } from 'react';
import { useAppDispatch, useAppSelector } from '../store';
import {
  addGlobalFilter,
  removeGlobalFilter,
  clearGlobalFilters,
  clearFiltersBySource,
  applyChartClickFilter,
} from '../store/slices/filterSlice';
import { Filter } from '../types';

export const useChartFilters = (chartId?: string) => {
  const dispatch = useAppDispatch();
  const globalFilters = useAppSelector((state) => state.filters.globalFilters);
  const activeFilterSource = useAppSelector((state) => state.filters.activeFilterSource);

  // Get filters applicable to this chart (excluding self-generated filters)
  const applicableFilters = useMemo(() => {
    if (!chartId) return globalFilters;
    return globalFilters.filter((f) => f.source !== chartId);
  }, [globalFilters, chartId]);

  // Get filters generated by this chart
  const selfFilters = useMemo(() => {
    if (!chartId) return [];
    return globalFilters.filter((f) => f.source === chartId);
  }, [globalFilters, chartId]);

  const addFilter = useCallback(
    (filter: Omit<Filter, 'id'>) => {
      const newFilter: Filter = {
        ...filter,
        id: `${filter.field}-${Date.now()}`,
        source: chartId,
      };
      dispatch(addGlobalFilter(newFilter));
    },
    [dispatch, chartId]
  );

  const removeFilter = useCallback(
    (filterId: string) => {
      dispatch(removeGlobalFilter(filterId));
    },
    [dispatch]
  );

  const clearAllFilters = useCallback(() => {
    dispatch(clearGlobalFilters());
  }, [dispatch]);

  const clearMyFilters = useCallback(() => {
    if (chartId) {
      dispatch(clearFiltersBySource(chartId));
    }
  }, [dispatch, chartId]);

  const handleChartClick = useCallback(
    (field: string, value: string | number) => {
      if (!chartId) return;
      dispatch(applyChartClickFilter({ chartId, field, value }));
    },
    [dispatch, chartId]
  );

  const isFilterActive = useCallback(
    (field: string, value: string | number) => {
      return globalFilters.some(
        (f) => f.field === field && f.value === value && f.operator === 'eq'
      );
    },
    [globalFilters]
  );

  return {
    globalFilters,
    applicableFilters,
    selfFilters,
    activeFilterSource,
    addFilter,
    removeFilter,
    clearAllFilters,
    clearMyFilters,
    handleChartClick,
    isFilterActive,
    hasActiveFilters: globalFilters.length > 0,
    isSourceOfActiveFilter: chartId === activeFilterSource,
  };
};
